apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openfindbearings-admin-ingress
  namespace: openfindbearings
  labels:
    name: openfindbearings-admin-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - admin.515813.xyz
    secretName: admin-515813-xyz-tls

  rules:
  - host: "admin.515813.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: openfindbearings-admin
              port:
                number: 80