apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
  namespace: openfindbearings
type: Opaque
stringData:
  connection-string: "Host=postgres;Port=5432;Database=db_admin;Username=postgres;Password=changeme"
