apiVersion: v1
kind: Secret
metadata:
  name: openfindbearings-admin-secrets
  namespace: openfindbearings
type: Opaque
stringData:
  connection-string: "Host=postgres;Port=5432;Database=db_admin;Username=postgres;Password=changeme;Timezone=UTC"
  Identity__ClientSecret: "<OAuth 客户端密钥>"
